### ISSUE TITLE
DPad not working

### ISSUE THREAD

**Issue by Melechtna** [qawse3dr/dkms-hid-nintendo-n64-and-segs-gen-support#4]
Hey, not sure if you're still on this anymore, but it does still work with the 6.0 kernel. Regardless, the dpads aren't wanting to function, though everything else works nearly flawlessly. Not sure why this is the case.

**Comment by qawse3dr** [comment]
Haven't touched it in a while and I am still on kernel 5.14 and was working last time I used it. but I might have a computer I can update. what dpad isn't working n64, or Sega gen?

**Comment by qawse3dr** [comment]
@Melechtna  I just tried using my n64 controller on retroarch and the dpad seems to be working fine with my kernel 6.0.8-1-MANJARO. and I have played a few sega games with the dpad before so I assume that's fine. Please let me know if there is some setup to help you will. Ill leave this thread open till after Christmas because it took me so long to get back to you (sorry for that)

**Comment by Melechtna** [comment]
> @Melechtna I just tried using my n64 controller on retroarch and the dpad seems to be working fine with my kernel 6.0.8-1-MANJARO. and I have played a few sega games with the dpad before so I assume that's fine. Please let me know if there is some setup to help you will. Ill leave this thread open till after Christmas because it took me so long to get back to you (sorry for that)

It turned out it was Retroarch being stupid, it kept switching back to another controller I keep plugged in, I completely forgot I opened the issue here.

**Comment by qawse3dr** [comment]
Ah okay sounds good. Glad to hear it works!
